a = input()
a = a.replace("c=","1")
a = a.replace("c-","2")
a = a.replace("dz=","3")
a = a.replace("d-","4")
a = a.replace("lj","5")
a = a.replace("nj","6")
a = a.replace("s=","7")
a = a.replace("z=","8")
print(len(a))